version: '3'
services:
  nginx:
    container_name: v-nginx
    image: nginx:1.13
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d

  mysql:
    container_name: v-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: car_park
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    restart: always

  app:
    restart: always
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    expose:
      - "8080"
    depends_on:
      - nginx
      - mysql
    command: gradle bootRun --args='--spring.profiles.active=api'