version: '3'
services:

  mysql:
    container_name: v-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: car_park
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    restart: always

  app:
    restart: always
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - mysql